### ISSUE TITLE
After installing this program, "ddl" command is not found

### ISSUE THREAD

**Issue by MVPAIR** [hwfan/DriveDownloader#10]
Can you help me
![image](https://github.com/hwfan/DriveDownloader/assets/98071184/979f176e-f0e4-4a54-97d4-04e32e2bcdb2)

**Comment by MVPAIR** [comment]
Yeah, i have solved it, to use it on windows, need to add this Script's path (C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts) to environment variable. Then edit the settings.py 's 89th line, due to Windows uses USERPROFILE, instead of HOME. Windows doesn't have HOME, so change os.environ["HOME"] to os.path.expanduser('~').

**Comment by hwfan** [comment]
Thank you for sharing! You can submit this change as a pull request, and in this way you can be included to the contributors of DriveDownloader. ;-)
