### ISSUE TITLE
请问对于dropbox 链接中带有rlkey的文件夹也能下载吗？

### ISSUE THREAD

**Issue by Thermaloo** [hwfan/DriveDownloader#12]
作者您好，最近我想在dropbox中下载一些数据，但是我尝试使用各种方法都失败了，我想请问一下该repo是不是可以下载任何dropbox中的文件或文件夹？如：https://www.dropbox.com/scl/fo/ajgcxsec1cojohdvn3dfd/h?dl=0&e=1&preview=Evaluation.zip&rlkey=2tnehx3ixc3ue7nne4yvflhd0

**Comment by hwfan** [comment]
Hi, I have only tested downloading single file on dropbox. In the next version this may be a new feature, stay tuned :-)
